next_image:
  name: Volgende afbeelding
  description: Wissel direct naar de volgende afbeelding voor één of meer image-entiteiten.
  fields:
    entity_id:
      name: Image entiteit
      required: false
      selector:
        entity:
          multiple: true
          filter:
            domain: image
